### ISSUE TITLE
About VLSC dataset

### ISSUE THREAD

**Issue by luffy-yu** [amber0309/Domain-generalization#1]
Where to download the original images of the VLSC dataset?

I figure out some URLs, might wrong, through my endeavor.
 
[VOC2007](http://host.robots.ox.ac.uk/pascal/VOC/voc2007/)
[LabelMe](http://www.ais.uni-bonn.de/download/datasets.html)
[SUN09](http://groups.csail.mit.edu/vision/Hcontext/data/sun09.tar)
[Caltech-101]( http://www.vision.caltech.edu/Image_Datasets/Caltech101/Caltech101.html)

BUT, why don't they contain the five classes('bird', 'car', 'chair', 'dog', 'person')?

**Comment by divyat09** [comment]
I think you can download the VLCS dataset following this repository: https://github.com/belaalb/G2DM

This link should work: http://www.mediafire.com/file/7yv132lgn1v267r/vlcs.tar.gz/file
