### ISSUE TITLE
Request to add our paper on Domain Generalisation

### ISSUE THREAD

**Issue by prinshul** [amber0309/Domain-generalization#12]
Thank you for your huge efforts in maintaining such a useful repository.

Can you pease add our CVPR 2021 Oral paper on Domain Generalisation:
Domain Generalization via Inference-time Label-Preserving Target Projections

https://arxiv.org/abs/2103.01134

**Comment by amber0309** [comment]
Sure.

Kind of busy recently. Will update your paper in a few days.

**Comment by amber0309** [comment]
> Thank you for your huge efforts in maintaining such a useful repository.
> 
> Can you pease add our CVPR 2021 Oral paper on Domain Generalisation:
> Domain Generalization via Inference-time Label-Preserving Target Projections
> 
> https://arxiv.org/abs/2103.01134

Hi @prinshul , paper added. Please check it out. :)

**Comment by prinshul** [comment]
> > Thank you for your huge efforts in maintaining such a useful repository.
> > Can you pease add our CVPR 2021 Oral paper on Domain Generalisation:
> > Domain Generalization via Inference-time Label-Preserving Target Projections
> > https://arxiv.org/abs/2103.01134
> 
> Hi @prinshul , paper added. Please check it out. :)

Thank you
