### ISSUE TITLE
Add a new CVPR2021 paper

### ISSUE THREAD

**Issue by SikaStar** [amber0309/Domain-generalization#13]
Hi, your collection is wonderful!
Please add a new paper "Generalizable Person Re-identification with Relevance-aware Mixture of Experts" (CVPR 2021) [paper link](https://openaccess.thecvf.com/content/CVPR2021/html/Dai_Generalizable_Person_Re-Identification_With_Relevance-Aware_Mixture_of_Experts_CVPR_2021_paper.html) In this paper, we aim to tackle the problem of domain generalization (DG) in person re-identification (re-ID). Specifically, we propose a novel mixture-of-experts paradigm via an effective voting-based mixture mechanism, which considers domains' relevance and performs in a meta-learning manner.

**Comment by amber0309** [comment]
Thanks for your info. Since it's not in the standard DG context, I added to the section of *DG variants*
