### ISSUE TITLE
GeoYFCC

### ISSUE THREAD

**Issue by abhimanyudubey** [amber0309/Domain-generalization#14]
Hi, thanks for maintaining this list. I'd like to point your attention to our new dataset GeoYFCC, an ImageNet-sized dataset for domain generalization, with ~62 domains at [this git repo](https://github.com/abhimanyudubey/GeoYFCC). For more details please refer to our CVPR 2021 paper [Adaptive Methods for Real-World Domain Generalization]( https://arxiv.org/pdf/2103.15796.pdf). Thanks!

**Comment by amber0309** [comment]
Done and thanks for your info!

If you'd like to add an entry for GeoYFCC in the table at section _Datasets_, please provide me detailed information of corresponding columns.

If not, you can close this issue. Thanks.
